Added optional eventName parameter
jorgecoca/lumberdash pull request #27
Opened 2019-10-09 21:44 UTC by erickjtorres

Added an optional eventName parameter in the Lumberdashclient so the developer can specify the name of the event if they would so choose to. This is specifically useful for firebase since you can log multiple events and as a developer, I would like to have the ability to name all my events differently.

Feedback is appreciated

2019-10-09 21:48 UTC, noahmateen approved these changes

2019-10-10 02:17 UTC, tchabot22 approved these changes

2019-10-10 02:19 UTC, felangel commented on lib/src/client/lumberdash_client.dart
>    /// and context of your log.
can we update the documentation above to explain the role of `eventName`?

2019-10-10 02:23 UTC, felangel requested changes
I think we should update the documentation

2019-10-10 14:11 UTC, XinfengMa commented
I don't think eventName should be optional though because for firebase analytics logEvent name is a required: https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.html#logEvent(java.lang.String,%20android.os.Bundle)
also I think parameter message is an optional, it could be part of extras with key "message"

2019-10-10 14:18 UTC, noahmateen requested changes
Based on Xinfengs feedback, lets make that change

2019-10-10 14:23 UTC, jorgecoca commented
@XinfengMa @noahmateen Since lumberdash is an abstraction over other libraries, we cannot let implementation details of other frameworks, such as firebase, dictate the API of the base client.
Maybe the naming could be improved, but adding the event name as not optional just because we need it for firebase is not the right answer, since other clients, such as sentry, or the simple client don't need it. That's why I think an optional parameter is a better option.

2019-10-10 17:50 UTC, XinfengMa commented
@jorgecoca Just like you mentioned, lumberdash is abstract layer, seems like abstract a required parameter to an optional one is wrong approach.  I totally understand if we abstract an optional parameter to a required one, not other way around though.  Anyway I don't think this is the place to make the change.  Look at the code of FirebaseLumberdash, we're using loggerName as eventName there.

2019-10-10 18:22 UTC, erickjtorres commented
> @jorgecoca Just like you mentioned, lumberdash is abstract layer, seems like abstract a required parameter to an optional one is wrong approach. I totally understand if we abstract an optional parameter to a required one, not other way around though. Anyway I don't think this is the place to make the change. Look at the code of FirebaseLumberdash, loggerName is used to log eventName there: https://pub.dev/documentation/firebase_lumberdash/latest/firebase_lumberdash/FirebaseLumberdash/logMessage.html

@XinfengMa I think the problem is that it's not always required and so we want to keep it optional. It also prevents us from breaking the current API for anyone that is currently using this. In the case of FirebaseLumberdash I'm creating a follow up PR to change the loggerName to being the value it defaults to if eventName is not provided.

2019-10-10 18:46 UTC, XinfengMa commented
@erickjtorres just felt the abstraction is more tuned to Sentry rather Firebase.  Don't think it is a good abstraction.  logEvent is very common among most of logging frameworks, maybe create a new method?  Anyway if everybody else is OK with the current approach, I won't bee the holdout.

2019-10-10 18:59 UTC, erickjtorres commented
> @erickjtorres just felt the abstraction is more tuned to Sentry rather Firebase. Don't think it is a good abstraction. logEvent is very common among most of logging frameworks, maybe create a new method? Anyway if everybody else is OK with the current approach, I won't bee the holdout.

Makes sense. I'm okay changing the approach or leaving it as is and coming up with a better approach later

2019-10-11 11:48 UTC, jorgecoca commented
Ok, team, here's the approach we are going to take: I am going to close this PR, and let's plan for a V2. I am going to open an issue on Github where we can discuss what the API should be knowing what we know already about all the clients.

On Monday, after the design phase, we can work on making the changes.

Thank you!

2019-10-11 11:48 UTC, closed without merging

2019-10-11 12:12 UTC, jorgecoca commented
Let's continue the conversation in #28